name: control_car
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  fl_chart: ^0.71.0
  cupertino_icons: ^1.0.8
  lucide_icons: ^0.257.0
  intl: ^0.20.2
  google_maps_flutter: ^2.12.1
  http: ^1.3.0
  table_calendar: ^3.2.0
  firebase_core: ^2.32.0
  firebase_auth: ^4.17.9
  cloud_firestore: ^4.15.9
  firebase_database: ^10.5.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/bako.png
    - assets/bee_vert.png
    - assets/bvan.png
    - assets/b1.png
    - assets/bee.png
    - assets/beee.png
    - assets/images/logo.png